plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = "com.fhk.security"
version = "1.0.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {

    implementation files("libs/fhk-common-1.0.0-plain.jar")

    // Api, Exception 관련
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // ConfigurationProperties 처리
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    // 스프링 (autoconfigure, security, redis)
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'  // 테스트용 추가
    testAnnotationProcessor 'org.projectlombok:lombok'   // 테스트용 추가

    // jwt 토큰
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}

tasks.named("bootJar") {
    enabled = false
}

tasks.named("jar") {
    enabled = true
}

test {
    useJUnitPlatform()
}